import { Product } from "./types";

export const mockProducts: Product[] = [
  {
    id: "p1",
    name: "Premium Wireless Headphones",
    description: "Experience immersive sound with our premium wireless headphones featuring noise cancellation technology.",
    price: 299.99,
    discountPrice: 249.99,
    category: "Electronics",
    brand: "SoundMaster",
    images: [
      "https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/3394651/pexels-photo-3394651.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/3394654/pexels-photo-3394654.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    rating: 4.8,
    reviewCount: 345,
    inStock: true,
    freeShipping: true,
    isNew: false,
    featured: true,
    features: [
      "Active Noise Cancellation",
      "40 hours battery life",
      "Bluetooth 5.2",
      "Built-in microphone",
      "Touch controls",
    ],
  },
  {
    id: "p2",
    name: "Ultra HD Smart TV 55-inch",
    description: "Transform your home entertainment with this stunning 4K Ultra HD Smart TV featuring vibrant colors and smart functionality.",
    price: 699.99,
    category: "Electronics",
    brand: "ViewTech",
    images: [
      "https://images.pexels.com/photos/5552789/pexels-photo-5552789.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/6782570/pexels-photo-6782570.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    rating: 4.5,
    reviewCount: 128,
    inStock: true,
    freeShipping: true,
    isNew: false,
    featured: true,
    features: [
      "4K Ultra HD resolution",
      "Smart TV with voice control",
      "HDR technology",
      "Multiple HDMI and USB ports",
      "Built-in streaming apps",
    ],
  },
  {
    id: "p3",
    name: "Luxury Watch Collection - Gold Edition",
    description: "Elegant timepiece crafted with precision and style. Features premium materials and Swiss movement.",
    price: 899.99,
    discountPrice: 699.99,
    category: "Fashion",
    brand: "Luxetime",
    images: [
      "https://images.pexels.com/photos/9978722/pexels-photo-9978722.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/9978675/pexels-photo-9978675.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    rating: 4.9,
    reviewCount: 87,
    inStock: true,
    freeShipping: true,
    isNew: false,
    featured: true,
    features: [
      "Swiss movement",
      "Gold-plated stainless steel",
      "Sapphire crystal glass",
      "Water-resistant up to 50m",
      "2-year warranty",
    ],
  },
  {
    id: "p4",
    name: "Professional Chef Kitchen Knife Set",
    description: "Premium 8-piece knife set for culinary enthusiasts. Precision-forged blades for perfect cutting every time.",
    price: 199.99,
    category: "Home & Kitchen",
    brand: "CulinaryPro",
    images: [
      "https://images.pexels.com/photos/6401669/pexels-photo-6401669.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/6401671/pexels-photo-6401671.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    rating: 4.7,
    reviewCount: 215,
    inStock: true,
    freeShipping: false,
    isNew: false,
    featured: false,
    features: [
      "8-piece professional set",
      "German stainless steel",
      "Ergonomic handles",
      "Includes knife sharpener",
      "Wooden storage block",
    ],
  },
  {
    id: "p5",
    name: "Premium Skincare Bundle",
    description: "Complete skincare routine with cleanser, toner, serum, and moisturizer. Made with natural ingredients for all skin types.",
    price: 89.99,
    discountPrice: 69.99,
    category: "Beauty",
    brand: "NaturGlow",
    images: [
      "https://images.pexels.com/photos/6621462/pexels-photo-6621462.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/5570080/pexels-photo-5570080.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    rating: 4.6,
    reviewCount: 178,
    inStock: true,
    freeShipping: true,
    isNew: true,
    featured: true,
    features: [
      "All-natural ingredients",
      "Paraben and sulfate-free",
      "Not tested on animals",
      "Suitable for all skin types",
      "Travel-friendly sizes",
    ],
  },
  {
    id: "p6",
    name: "Carbon Fiber Road Bike",
    description: "Lightweight carbon fiber road bike designed for speed and performance. Features premium components and sleek design.",
    price: 1899.99,
    category: "Sports",
    brand: "VeloTech",
    images: [
      "https://images.pexels.com/photos/1413412/pexels-photo-1413412.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/5465304/pexels-photo-5465304.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    rating: 4.8,
    reviewCount: 56,
    inStock: false,
    freeShipping: true,
    isNew: false,
    featured: false,
    features: [
      "Carbon fiber frame",
      "Shimano gear system",
      "Hydraulic disc brakes",
      "Aerodynamic design",
      "Professional racing saddle",
    ],
  },
  {
    id: "p7",
    name: "Classic Literary Collection Box Set",
    description: "Beautifully bound collection of classic literature, featuring works from renowned authors throughout history.",
    price: 129.99,
    discountPrice: 99.99,
    category: "Books",
    brand: "Heritage Books",
    images: [
      "https://images.pexels.com/photos/1130980/pexels-photo-1130980.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/694740/pexels-photo-694740.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    rating: 4.7,
    reviewCount: 89,
    inStock: true,
    freeShipping: true,
    isNew: false,
    featured: false,
    features: [
      "10-volume collection",
      "Hardcover with gold embossing",
      "Archival-quality paper",
      "Ribbon bookmarks",
      "Collector's edition",
    ],
  },
  {
    id: "p8",
    name: "Interactive Smart Home Hub",
    description: "Control your entire home with this advanced smart home hub. Compatible with most smart devices and voice assistants.",
    price: 249.99,
    category: "Electronics",
    brand: "SmartLife",
    images: [
      "https://images.pexels.com/photos/4790255/pexels-photo-4790255.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/3689532/pexels-photo-3689532.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    rating: 4.4,
    reviewCount: 145,
    inStock: true,
    freeShipping: true,
    isNew: true,
    featured: true,
    features: [
      "Compatible with over 1000 smart devices",
      "Voice control integration",
      "Mobile app control",
      "Energy monitoring",
      "Customizable automations",
    ],
  },
  {
    id: "p9",
    name: "Designer Leather Handbag",
    description: "Handcrafted luxury leather handbag with signature gold hardware. Spacious interior with multiple compartments.",
    price: 499.99,
    discountPrice: 399.99,
    category: "Fashion",
    brand: "Eleganza",
    images: [
      "https://images.pexels.com/photos/5706248/pexels-photo-5706248.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/10006828/pexels-photo-10006828.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    rating: 4.9,
    reviewCount: 72,
    inStock: true,
    freeShipping: true,
    isNew: false,
    featured: true,
    features: [
      "Genuine full-grain leather",
      "Gold-plated hardware",
      "Multiple interior compartments",
      "Adjustable shoulder strap",
      "Dust bag included",
    ],
  },
  {
    id: "p10",
    name: "Modern Accent Chair",
    description: "Stylish mid-century inspired accent chair with comfortable upholstery. Perfect addition to any living space.",
    price: 349.99,
    category: "Home & Kitchen",
    brand: "ModernLiving",
    images: [
      "https://images.pexels.com/photos/1866149/pexels-photo-1866149.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/6492397/pexels-photo-6492397.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    rating: 4.5,
    reviewCount: 128,
    inStock: true,
    freeShipping: false,
    isNew: false,
    featured: false,
    features: [
      "Solid wood frame",
      "Premium upholstery",
      "Ergonomic design",
      "Assembly required",
      "Available in multiple colors",
    ],
  },
  {
    id: "p11",
    name: "Professional Digital Camera Kit",
    description: "Complete professional photography kit with high-resolution digital camera, multiple lenses, and accessories.",
    price: 1299.99,
    discountPrice: 1099.99,
    category: "Electronics",
    brand: "OptiPro",
    images: [
      "https://images.pexels.com/photos/225157/pexels-photo-225157.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/51383/photo-camera-subject-photographer-51383.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    rating: 4.7,
    reviewCount: 95,
    inStock: true,
    freeShipping: true,
    isNew: false,
    featured: true,
    features: [
      "24MP full-frame sensor",
      "4K video capability",
      "3 premium lenses included",
      "Weather-sealed body",
      "1-year professional warranty",
    ],
  },
  {
    id: "p12",
    name: "Luxury Scented Candle Collection",
    description: "Set of premium hand-poured scented candles in elegant glass containers. Perfect for creating a relaxing atmosphere.",
    price: 79.99,
    category: "Home & Kitchen",
    brand: "AromaLux",
    images: [
      "https://images.pexels.com/photos/3270223/pexels-photo-3270223.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
      "https://images.pexels.com/photos/4195342/pexels-photo-4195342.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2",
    ],
    rating: 4.6,
    reviewCount: 167,
    inStock: true,
    freeShipping: true,
    isNew: true,
    featured: false,
    features: [
      "Set of 4 unique scents",
      "Natural soy wax",
      "40-hour burn time each",
      "Reusable glass containers",
      "Gift box included",
    ],
  },
];